import type { Catalog } from "../lib/types";
export const demoCatalog: Catalog = {
  demo: true,
  categories: [
    { id: "home", name: "บ้าน & ไลฟ์สไตล์", sortOrder: 0, revision: 1 },
    { id: "beauty", name: "บิวตี้ & ดูแลตัวเอง", sortOrder: 1, revision: 1 },
    { id: "cat", name: "ของน้องแมว", sortOrder: 2, revision: 1 },
    { id: "cute", name: "ของน่ารัก", sortOrder: 3, revision: 1 },
  ],
  settings: {
    id: "main",
    siteName: "น้ำหวานคัดให้",
    tagline: "ของน่ารักที่อยากบอกต่อ ♡",
    introduction:
      "ค่อย ๆ เลือกของที่ชอบ แล้วส่งต่อให้คุณ มีทั้งของใช้ประจำวันและความน่ารักเล็ก ๆ ที่ทำให้วันธรรมดาพิเศษขึ้น",
    bannerUrl: "",
    affiliateDisclosure:
      "ลิงก์บางรายการเป็นลิงก์ affiliate เราอาจได้รับค่าคอมมิชชันเมื่อคุณซื้อผ่านลิงก์ ราคาและโปรโมชันอาจเปลี่ยนแปลง กรุณาตรวจสอบที่ Shopee",
    revision: 1,
  },
  products: [
    {
      id: "demo-1",
      categoryId: "home",
      name: "แก้วเซรามิกสำหรับเช้าที่สดใส",
      description:
        "ตัวอย่างสินค้า — แทนที่ด้วยสินค้าที่คุณแนะนำได้ในหน้าแอดมิน",
      recommendation: "จิบกาแฟแล้วใจฟู สีละมุนเข้ากับทุกมุมบ้าน",
      price: 189,
      imageUrl: "/images/mug.svg",
      affiliateUrl: "",
      featured: true,
      published: true,
      sortOrder: 0,
      revision: 1,
    },
    {
      id: "demo-2",
      categoryId: "cute",
      name: "กระเป๋าผ้าเพื่อนแมว",
      description: "ตัวอย่างสินค้า",
      recommendation: "พกของชิ้นเล็กไปไหนก็สะดวก พร้อมเพื่อนแมวน่ารัก",
      price: 129,
      imageUrl: "/images/tote.svg",
      affiliateUrl: "",
      featured: true,
      published: true,
      sortOrder: 1,
      revision: 1,
    },
    {
      id: "demo-3",
      categoryId: "cat",
      name: "ชามอาหารทรงน่ารักของน้องแมว",
      description: "ตัวอย่างสินค้า",
      recommendation: "มุมกินข้าวของเจ้าตัวเล็กก็น่ารักได้",
      price: 259,
      imageUrl: "/images/bowl.svg",
      affiliateUrl: "",
      featured: true,
      published: true,
      sortOrder: 2,
      revision: 1,
    },
    {
      id: "demo-4",
      categoryId: "beauty",
      name: "กระจกตั้งโต๊ะสีพีช",
      description: "ตัวอย่างสินค้า",
      recommendation: "เติมความละมุนให้มุมแต่งตัวในทุกวัน",
      price: 159,
      imageUrl: "/images/mirror.svg",
      affiliateUrl: "",
      featured: false,
      published: true,
      sortOrder: 3,
      revision: 1,
    },
    {
      id: "demo-5",
      categoryId: "home",
      name: "โคมไฟแสงอุ่นข้างเตียง",
      description: "ตัวอย่างสินค้า",
      recommendation: "เปิดไฟนุ่ม ๆ แล้วพักใจหลังวันยาว ๆ",
      price: 349,
      imageUrl: "/images/lamp.svg",
      affiliateUrl: "",
      featured: false,
      published: true,
      sortOrder: 4,
      revision: 1,
    },
    {
      id: "demo-6",
      categoryId: "cute",
      name: "สมุดบันทึกเรื่องเล็ก ๆ",
      description: "ตัวอย่างสินค้า",
      recommendation: "เก็บความคิดดี ๆ และลิสต์ของที่อยากได้",
      price: 89,
      imageUrl: "/images/notebook.svg",
      affiliateUrl: "",
      featured: false,
      published: true,
      sortOrder: 5,
      revision: 1,
    },
  ],
};
